### ISSUE TITLE
file("all_dependencies_genes_map.csv") not exist

### ISSUE THREAD

**Issue by clouwer** [qiaoliuhub/drug_combination#1]
when i run attention_main.py, I get the following error: FileNotFoundError: [Errno 2] File working_dir+"cl_gene_dp/all_dependencies_genes_map.csv".

How can I get all_dependencies_genes_map.csv？

**Comment by unclestrong** [comment]
hello，I can not get the dataset through 'zenodo_get 10.5281/zenodo.4789936',  this command shows **'Connection error'**, so could you have a favour to supply the dataset thorgh a netdisk link?
